#=================================================
#   Description: Build  X86-64固件 FROM LEAN'S LEDE
#   Author: JK
#=================================================

#=================================================
name: Build X86-64+passwall-20200708
#=================================================

on: 
  release:
    types: [published]
#  push:
#    branches: 
#      - master
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          hhvm \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev patch unzip lib32gcc1 libc6-dev-i386 subversion flex node-uglify gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils  libelf-dev autoconf automake libtool autopoint device-tree-compiler libuv-dev python3.6 zlib1g-dev upx-ucl node-uglify antlr3 gperf
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
        
        
    - name: Clone source code
      run: |
        git clone https://github.com/coolsnowwolf/lede lede
        
        ##修改lede目录中的feeds.conf.default文件，把第5行的 # 去掉。
        #cd lede
        #sed -i '5s/#//' feeds.conf.default
   
   
    - name: Clone SSR plus code
      run: |
        cd lede/package &&  git clone https://github.com/fw876/helloworld.git
   
        
    - name: Clone passwall code
      run: |
        cd lede/package &&  git clone https://github.com/chengood5000/passwall652.git
         ##下载别人备份的passwall源代码。
        
      
        
    - name: Update feeds
      run: cd lede && ./scripts/feeds update -a

    - name: Install feeds
      run: cd lede && ./scripts/feeds install -a


####********************************************************************************************
    - name: delete smartdns code
      run: |
        cd lede/feeds/packages/net &&  rm -rf smartdns

    - name: Clone luci-app-smartdns code
      run: |
        cd lede/package &&  git clone https://github.com/romantices/luci-app-smartdns-lede.git
    
    - name: Clone smartdns code
      run: |
        cd lede/package &&  git clone https://github.com/romantices/smartdns.git


####********************************************************************************************


    - name: Load custom configuration
      run: |
        #=================================================
        #+++++++++++++++++++++++++++++++++++++++++++++++++
        cp -f X86.config ./lede/.config
        chmod +x diy-newifi3.sh
        cd lede
        ../diy-newifi3.sh
        #++++++++++++++++++++++++++++++++++++++++++++++++
        #=================================================
        make defconfig
    - name: Download package
      run: |
        echo -e "$(nproc) thread build."
        cd lede && make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    - name: Build
      run: |
        cd lede
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s
 
 ######把上面生成的.config文件拷贝到bin/targets/x86/64/my.config，从而在下载固件时，一起下载回来。
    - name: Copy .config  to  ./bin/targets/x86/64/my.config
      run: |
        cd lede
        cp  .config   ./bin/targets/x86/64/my.config  
   
   
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        #=================================================
        name: X86-64+passwall-20200708
        path: ./lede/bin
